"""Add is_archived and interview_type to jobs

Revision ID: 1e23b104171d
Revises: 2d028c401055
Create Date: 2026-06-19 10:30:31.121387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e23b104171d'
down_revision: Union[str, Sequence[str], None] = '2d028c401055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('interview_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_archived')
    op.drop_column('jobs', 'interview_type')
    # ### end Alembic commands ###
