"""Add recruiter_id to candidate and job

Revision ID: 2d028c401055
Revises: 093bbcf27dae
Create Date: 2026-06-19 05:02:12.367326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d028c401055'
down_revision: Union[str, Sequence[str], None] = '093bbcf27dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('recruiter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_candidates_recruiter_id'), 'candidates', ['recruiter_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'recruiters', ['recruiter_id'], ['id'], ondelete='CASCADE')
    op.add_column('jobs', sa.Column('recruiter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_recruiter_id'), 'jobs', ['recruiter_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'recruiters', ['recruiter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_recruiter_id'), table_name='jobs')
    op.drop_column('jobs', 'recruiter_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_recruiter_id'), table_name='candidates')
    op.drop_column('candidates', 'recruiter_id')
    # ### end Alembic commands ###
