"""add zoom_meeting_id to sessions

Revision ID: 302919e8d340
Revises: 8974fe984472
Create Date: 2026-05-22 13:42:07.311364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302919e8d340'
down_revision: Union[str, Sequence[str], None] = '8974fe984472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('zoom_meeting_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sessions_zoom_meeting_id'), 'sessions', ['zoom_meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_zoom_meeting_id'), table_name='sessions')
    op.drop_column('sessions', 'zoom_meeting_id')
    # ### end Alembic commands ###
