"""add meeting_provider to sessions

Revision ID: 33cf05e58724
Revises: aa7a7ec0e2e5
Create Date: 2026-06-29 09:35:25.105008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cf05e58724'
down_revision: Union[str, Sequence[str], None] = 'aa7a7ec0e2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('meeting_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'meeting_provider')
    # ### end Alembic commands ###
