"""Add ai_runtime_status to Session

Revision ID: 622b2a20d718
Revises: d8f3a9b7c1e2
Create Date: 2026-06-26 05:19:00.910777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622b2a20d718'
down_revision: Union[str, Sequence[str], None] = 'd8f3a9b7c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('ai_runtime_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ai_runtime_status')
    # ### end Alembic commands ###
