"""Add candidate management fields

Revision ID: 6741af1c4dc3
Revises: 1e23b104171d
Create Date: 2026-06-22 06:36:32.606892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6741af1c4dc3'
down_revision: Union[str, Sequence[str], None] = '1e23b104171d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('status', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('resume_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'resume_url')
    op.drop_column('candidates', 'status')
    op.drop_column('candidates', 'notes')
    op.drop_column('candidates', 'phone')
    # ### end Alembic commands ###
