"""Add RecruiterZoomToken

Revision ID: aa7a7ec0e2e5
Revises: 622b2a20d718
Create Date: 2026-06-28 11:40:06.399390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7a7ec0e2e5'
down_revision: Union[str, Sequence[str], None] = '622b2a20d718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_zoom_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_access_token', sa.String(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('zoom_user_id', sa.String(), nullable=False),
    sa.Column('zoom_email', sa.String(), nullable=True),
    sa.Column('token_scope', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_zoom_tokens_recruiter_id'), 'recruiter_zoom_tokens', ['recruiter_id'], unique=True)
    op.create_index(op.f('ix_recruiter_zoom_tokens_zoom_user_id'), 'recruiter_zoom_tokens', ['zoom_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiter_zoom_tokens_zoom_user_id'), table_name='recruiter_zoom_tokens')
    op.drop_index(op.f('ix_recruiter_zoom_tokens_recruiter_id'), table_name='recruiter_zoom_tokens')
    op.drop_table('recruiter_zoom_tokens')
    # ### end Alembic commands ###
