"""add jobs table and session job fields

Revision ID: cd887836b37d
Revises: 302919e8d340
Create Date: 2026-05-25 12:16:05.067564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd887836b37d'
down_revision: Union[str, Sequence[str], None] = '302919e8d340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('extracted_skills', sa.JSON(), nullable=True),
    sa.Column('seniority_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sessions', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'scheduled_at')
    op.drop_column('sessions', 'job_id')
    op.drop_table('jobs')
    # ### end Alembic commands ###
